# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vipin GS Notes
email: mail@vipings.com
logo: "/assets/images/logo.jpg"
#baseurl "" # the subpath of your site, e.g. /blog
url: "https://vipings.com" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Vipin G S'
#bio:Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
#author_image:"/assets/images/author.jpg"
github_username: mnbvcxz010308

# Google Analytics
analytics_id: "UA-108813279-1"

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true

gems:
  - jekyll-paginate
